on: 
  workflow_dispatch:
  release:
    types: [created]

jobs:
  upload_asset:
    runs-on: ubuntu-latest
    name: Test asset upload
    steps:
    - uses: actions/checkout@v2
    - name: upload reame
      uses: actions/qm-release-upload-asset@v1
      with:
        paths: ['./README.md']

    
